#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-oro
Version  : 2.0.8
Release  : 2
URL      : https://repo1.maven.org/maven2/oro/oro/2.0.8/oro-2.0.8.jar
Source0  : https://repo1.maven.org/maven2/oro/oro/2.0.8/oro-2.0.8.jar
Source1  : https://repo1.maven.org/maven2/oro/oro/2.0.8/oro-2.0.8.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-1.1
Requires: mvn-oro-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-oro package.
Group: Data

%description data
data components for the mvn-oro package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/oro/oro/2.0.8
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/oro/oro/2.0.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/oro/oro/2.0.8
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/oro/oro/2.0.8


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar
/usr/share/java/.m2/repository/oro/oro/2.0.8/oro-2.0.8.pom
